-- Insert scraped hobbies from allpastimes.com
-- Run this in your Supabase SQL console to add 500+ new hobby categories

INSERT INTO categories (name, slug, description, emoji, color)
VALUES
  ('3d Printing', '3d-printing', 'Terms and activities related to 3d printing', '🖨️', 'teal'),
  ('A Capella', 'a-capella', 'Terms and activities related to a capella', '🎯', 'brown'),
  ('A Cappella', 'a-cappella', 'Terms and activities related to a cappella', '🎯', 'blue'),
  ('Abandoned Places Photography', 'abandoned-places-photography', 'Terms and activities related to abandoned places photography', '📷', 'blue'),
  ('Aboriginal Art', 'aboriginal-art', 'Terms and activities related to aboriginal art', '🎯', 'blue'),
  ('Abseiling', 'abseiling', 'Terms and activities related to abseiling', '🎯', 'orange'),
  ('Acoustic Guitar', 'acoustic-guitar', 'Terms and activities related to acoustic guitar', '🎯', 'orange'),
  ('Acro Dance', 'acro-dance', 'Terms and activities related to acro dance', '💃', 'red'),
  ('Acrobatics', 'acrobatics', 'Terms and activities related to acrobatics', '🎯', 'red'),
  ('Acroyoga', 'acroyoga', 'Terms and activities related to acroyoga', '🧘', 'gray'),
  ('Acrylic Painting', 'acrylic-painting', 'Terms and activities related to acrylic painting', '🎨', 'blue'),
  ('Acting', 'acting', 'Terms and activities related to acting', '🎯', 'red'),
  ('Adventure Racing', 'adventure-racing', 'Terms and activities related to adventure racing', '🎯', 'yellow'),
  ('Adventure Running', 'adventure-running', 'Terms and activities related to adventure running', '🏃', 'red'),
  ('Adventure Travel', 'adventure-travel', 'Terms and activities related to adventure travel', '🎯', 'purple'),
  ('Aerial Photography', 'aerial-photography', 'Terms and activities related to aerial photography', '📷', 'teal'),
  ('Aerial Silks', 'aerial-silks', 'Terms and activities related to aerial silks', '🎯', 'pink'),
  ('Aeromodelling', 'aeromodelling', 'Terms and activities related to aeromodelling', '🎯', 'gray'),
  ('Air Racing', 'air-racing', 'Terms and activities related to air racing', '🎯', 'blue'),
  ('Air Sports', 'air-sports', 'Terms and activities related to air sports', '🎯', 'yellow'),
  ('Airbrushing', 'airbrushing', 'Terms and activities related to airbrushing', '🎯', 'purple'),
  ('Alpine Skiing', 'alpine-skiing', 'Terms and activities related to alpine skiing', '⛷️', 'indigo'),
  ('Amateur Detective', 'amateur-detective', 'Terms and activities related to amateur detective', '🎯', 'gray'),
  ('Amateur Geology', 'amateur-geology', 'Terms and activities related to amateur geology', '🎯', 'brown'),
  ('Amateur Radio', 'amateur-radio', 'Terms and activities related to amateur radio', '🎯', 'blue'),
  ('Ambient Music', 'ambient-music', 'Terms and activities related to ambient music', '🎵', 'purple'),
  ('American Football', 'american-football', 'Terms and activities related to american football', '🏈', 'orange'),
  ('Amigurumi Art', 'amigurumi-art', 'Terms and activities related to amigurumi art', '🎨', 'pink'),
  ('Angling', 'angling', 'Terms and activities related to angling', '🎯', 'blue'),
  ('Animal Fancy', 'animal-fancy', 'Terms and activities related to animal fancy', '🎯', 'green'),
  ('Animal Husbandry', 'animal-husbandry', 'Terms and activities related to animal husbandry', '🎯', 'brown'),
  ('Animal Watching', 'animal-watching', 'Terms and activities related to animal watching', '🎯', 'green'),
  ('Ant-keeping', 'ant-keeping', 'Terms and activities related to ant-keeping', '🎯', 'brown'),
  ('Antarctica Marathon', 'antarctica-marathon', 'Terms and activities related to antarctica marathon', '🏃', 'blue'),
  ('Anti-gravity Cocooning', 'anti-gravity-cocooning', 'Terms and activities related to anti-gravity cocooning', '🎯', 'purple'),
  ('Antiquing', 'antiquing', 'Terms and activities related to antiquing', '🎯', 'brown'),
  ('Appalachian Dulcimer', 'appalachian-dulcimer', 'Terms and activities related to appalachian dulcimer', '🎯', 'brown'),
  ('Aquascaping', 'aquascaping', 'Terms and activities related to aquascaping', '🎯', 'blue'),
  ('Arcade Games', 'arcade-games', 'Terms and activities related to arcade games', '🎮', 'red'),
  ('Archery', 'archery', 'Terms and activities related to archery', '🏹', 'green'),
  ('Architectural Models', 'architectural-models', 'Terms and activities related to architectural models', '🔨', 'gray'),
  ('Argentine Tango', 'argentine-tango', 'Terms and activities related to argentine tango', '💃', 'red'),
  ('Arm Wrestling', 'arm-wrestling', 'Terms and activities related to arm wrestling', '🎯', 'red'),
  ('Art Collecting', 'art-collecting', 'Terms and activities related to art collecting', '🎨', 'purple'),
  ('Art Gallery Visiting', 'art-gallery-visiting', 'Terms and activities related to art gallery visiting', '🎨', 'blue'),
  ('Artistic Swimming', 'artistic-swimming', 'Terms and activities related to artistic swimming', '🏊', 'blue'),
  ('Astrophotography', 'astrophotography', 'Terms and activities related to astrophotography', '📷', 'indigo'),
  ('Australian Football', 'australian-football', 'Terms and activities related to australian football', '🏈', 'orange'),
  ('Auto Detailing', 'auto-detailing', 'Terms and activities related to auto detailing', '🎯', 'blue'),
  ('Auto Racing', 'auto-racing', 'Terms and activities related to auto racing', '🎯', 'red'),
  ('Autograph Collecting', 'autograph-collecting', 'Terms and activities related to autograph collecting', '📦', 'yellow'),
  ('Automobile Restoration', 'automobile-restoration', 'Terms and activities related to automobile restoration', '🔨', 'brown'),
  ('Axe Throwing', 'axe-throwing', 'Terms and activities related to axe throwing', '🎯', 'brown'),
  ('Badminton', 'badminton', 'Terms and activities related to badminton', '🏸', 'yellow'),
  ('Baking', 'baking', 'Terms and activities related to baking', '🧁', 'pink'),
  ('Balloon Art', 'balloon-art', 'Terms and activities related to balloon art', '🎨', 'red'),
  ('Barefoot Running', 'barefoot-running', 'Terms and activities related to barefoot running', '🏃', 'green'),
  ('Bartending', 'bartending', 'Terms and activities related to bartending', '🎯', 'orange'),
  ('Base Jumping', 'base-jumping', 'Terms and activities related to base jumping', '🎯', 'blue'),
  ('Baseball', 'baseball', 'Terms and activities related to baseball', '⚾', 'red'),
  ('Basket Weaving', 'basket-weaving', 'Terms and activities related to basket weaving', '✂️', 'brown'),
  ('Basketball', 'basketball', 'Terms and activities related to basketball', '🏀', 'orange'),
  ('Beachcombing', 'beachcombing', 'Terms and activities related to beachcombing', '🎯', 'yellow'),
  ('Beading', 'beading', 'Terms and activities related to beading', '💎', 'purple'),
  ('Beekeeping', 'beekeeping', 'Terms and activities related to beekeeping', '🐝', 'yellow'),
  ('Beer Brewing', 'beer-brewing', 'Terms and activities related to beer brewing', '🍺', 'brown'),
  ('Bell Ringing', 'bell-ringing', 'Terms and activities related to bell ringing', '🎯', 'yellow'),
  ('Belly Dance', 'belly-dance', 'Terms and activities related to belly dance', '💃', 'pink'),
  ('Bicycling', 'bicycling', 'Terms and activities related to bicycling', '🚴', 'green'),
  ('Bird Watching', 'bird-watching', 'Terms and activities related to bird watching', '🦅', 'brown'),
  ('Blacksmithing', 'blacksmithing', 'Terms and activities related to blacksmithing', '⚒️', 'black'),
  ('Blogging', 'blogging', 'Terms and activities related to blogging', '✍️', 'blue'),
  ('Board Games', 'board-games', 'Terms and activities related to board games', '🎲', 'rainbow'),
  ('Board Sports', 'board-sports', 'Terms and activities related to board sports', '🎯', 'blue'),
  ('Bodyboarding', 'bodyboarding', 'Terms and activities related to bodyboarding', '🏄', 'teal'),
  ('Bodybuilding', 'bodybuilding', 'Terms and activities related to bodybuilding', '💪', 'red'),
  ('Book Restoration', 'book-restoration', 'Terms and activities related to book restoration', '📚', 'brown'),
  ('Bookbinding', 'bookbinding', 'Terms and activities related to bookbinding', '📚', 'brown'),
  ('Bouldering', 'bouldering', 'Terms and activities related to bouldering', '🧗', 'gray'),
  ('Bowling', 'bowling', 'Terms and activities related to bowling', '🎳', 'yellow'),
  ('Boxing', 'boxing', 'Terms and activities related to boxing', '🥊', 'red'),
  ('Bracelet Making', 'bracelet-making', 'Terms and activities related to bracelet making', '💎', 'pink'),
  ('Bread Making', 'bread-making', 'Terms and activities related to bread making', '🧁', 'brown'),
  ('Breakdancing', 'breakdancing', 'Terms and activities related to breakdancing', '💃', 'red'),
  ('Bungee Jumping', 'bungee-jumping', 'Terms and activities related to bungee jumping', '🤸‍♂️', 'orange'),
  ('Butterfly Watching', 'butterfly-watching', 'Terms and activities related to butterfly watching', '🎯', 'pink'),
  ('Button Collecting', 'button-collecting', 'Terms and activities related to button collecting', '📦', 'blue'),
  ('Cake Decorating', 'cake-decorating', 'Terms and activities related to cake decorating', '🧁', 'pink'),
  ('Camel Racing', 'camel-racing', 'Terms and activities related to camel racing', '🎯', 'brown'),
  ('Camping', 'camping', 'Terms and activities related to camping', '⛺', 'green'),
  ('Candle Making', 'candle-making', 'Terms and activities related to candle making', '✂️', 'yellow'),
  ('Canoeing', 'canoeing', 'Terms and activities related to canoeing', '🛶', 'blue'),
  ('Canyoning', 'canyoning', 'Terms and activities related to canyoning', '🧗', 'brown'),
  ('Card Making', 'card-making', 'Terms and activities related to card making', '✂️', 'purple'),
  ('Caravaning', 'caravaning', 'Terms and activities related to caravaning', '🎯', 'green'),
  ('Cardio Workout', 'cardio-workout', 'Terms and activities related to cardio workout', '💪', 'red'),
  ('Cartooning', 'cartooning', 'Terms and activities related to cartooning', '🎨', 'yellow'),
  ('Cave Diving', 'cave-diving', 'Terms and activities related to cave diving', '🤿', 'blue'),
  ('Cave Exploring', 'cave-exploring', 'Terms and activities related to cave exploring', '🎯', 'brown'),
  ('Ceramics', 'ceramics', 'Terms and activities related to ceramics', '🏺', 'brown'),
  ('Chainsaw Carving', 'chainsaw-carving', 'Terms and activities related to chainsaw carving', '🪵', 'brown'),
  ('Chalk Art', 'chalk-art', 'Terms and activities related to chalk art', '🎨', 'yellow'),
  ('Cheerleading', 'cheerleading', 'Terms and activities related to cheerleading', '💃', 'red'),
  ('Cheese Making', 'cheese-making', 'Terms and activities related to cheese making', '🧁', 'yellow'),
  ('Chess', 'chess', 'Terms and activities related to chess', '♟️', 'black'),
  ('Chocolate Making', 'chocolate-making', 'Terms and activities related to chocolate making', '🧁', 'brown'),
  ('Classical Music', 'classical-music', 'Terms and activities related to classical music', '🎵', 'blue'),
  ('Clay Pigeon Shooting', 'clay-pigeon-shooting', 'Terms and activities related to clay pigeon shooting', '🎯', 'orange'),
  ('Cliff Diving', 'cliff-diving', 'Terms and activities related to cliff diving', '🤿', 'blue'),
  ('Climbing', 'climbing', 'Terms and activities related to climbing', '🧗‍♀️', 'gray'),
  ('Clock Fixing', 'clock-fixing', 'Terms and activities related to clock fixing', '⚒️', 'brown'),
  ('Cloud Watching', 'cloud-watching', 'Terms and activities related to cloud watching', '🎯', 'blue'),
  ('Coffee Roasting', 'coffee-roasting', 'Terms and activities related to coffee roasting', '☕', 'brown'),
  ('Coin Collecting', 'coin-collecting', 'Terms and activities related to coin collecting', '🪙', 'gold'),
  ('Collage Art', 'collage-art', 'Terms and activities related to collage art', '🎨', 'rainbow'),
  ('Coloring', 'coloring', 'Terms and activities related to coloring', '🎨', 'rainbow'),
  ('Comic Books Collecting', 'comic-books-collecting', 'Terms and activities related to comic books collecting', '📦', 'blue'),
  ('Competitive Eating', 'competitive-eating', 'Terms and activities related to competitive eating', '🎯', 'orange'),
  ('Composting', 'composting', 'Terms and activities related to composting', '🪱', 'brown'),
  ('Computer Art', 'computer-art', 'Terms and activities related to computer art', '🎨', 'blue'),
  ('Computer Programming', 'computer-programming', 'Terms and activities related to computer programming', '💻', 'blue'),
  ('Concrete Art', 'concrete-art', 'Terms and activities related to concrete art', '🎨', 'gray'),
  ('Contemporary Dance', 'contemporary-dance', 'Terms and activities related to contemporary dance', '💃', 'purple'),
  ('Cooking', 'cooking', 'Terms and activities related to cooking', '👨‍🍳', 'orange'),
  ('Cosplay', 'cosplay', 'Terms and activities related to cosplay', '🦸', 'rainbow'),
  ('Couponing', 'couponing', 'Terms and activities related to couponing', '🎯', 'yellow'),
  ('Creative Writing', 'creative-writing', 'Terms and activities related to creative writing', '✍️', 'blue'),
  ('Cricket', 'cricket', 'Terms and activities related to cricket', '🏏', 'white'),
  ('Crocheting', 'crocheting', 'Terms and activities related to crocheting', '🧶', 'pink'),
  ('Cross Country Running', 'cross-country-running', 'Terms and activities related to cross country running', '🏃', 'green'),
  ('Cross-stitch', 'cross-stitch', 'Terms and activities related to cross-stitch', '🧵', 'pink'),
  ('Crossword Puzzles', 'crossword-puzzles', 'Terms and activities related to crossword puzzles', '📝', 'black'),
  ('Curling', 'curling', 'Terms and activities related to curling', '🥌', 'blue'),
  ('Cycling', 'cycling', 'Terms and activities related to cycling', '🚴', 'blue'),
  ('Dance', 'dance', 'Terms and activities related to dance', '💃', 'pink'),
  ('Darts', 'darts', 'Terms and activities related to darts', '🎯', 'red'),
  ('Decoupage', 'decoupage', 'Terms and activities related to decoupage', '✂️', 'pink'),
  ('Deep Sea Fishing', 'deep-sea-fishing', 'Terms and activities related to deep sea fishing', '🎣', 'blue'),
  ('Doll Collecting', 'doll-collecting', 'Terms and activities related to doll collecting', '📦', 'pink'),
  ('Drawing', 'drawing', 'Terms and activities related to drawing', '✏️', 'gray'),
  ('Drone Flying', 'drone-flying', 'Terms and activities related to drone flying', '🎯', 'blue'),
  ('Drums', 'drums', 'Terms and activities related to drums', '🥁', 'red'),
  ('Duck Calling', 'duck-calling', 'Terms and activities related to duck calling', '🎯', 'green'),
  ('Dungeons And Dragons', 'dungeons-and-dragons', 'Terms and activities related to dungeons and dragons', '🎲', 'purple'),
  ('Electronics', 'electronics', 'Terms and activities related to electronics', '🔌', 'yellow'),
  ('Embroidery', 'embroidery', 'Terms and activities related to embroidery', '🧵', 'pink'),
  ('Equestrianism', 'equestrianism', 'Terms and activities related to equestrianism', '🐴', 'brown'),
  ('Extreme Sports', 'extreme-sports', 'Terms and activities related to extreme sports', '🎯', 'orange'),
  ('Fashion Design', 'fashion-design', 'Terms and activities related to fashion design', '👗', 'pink'),
  ('Fencing', 'fencing', 'Terms and activities related to fencing', '🤺', 'white'),
  ('Figure Skating', 'figure-skating', 'Terms and activities related to figure skating', '⛸️', 'blue'),
  ('Film Making', 'film-making', 'Terms and activities related to film making', '🎬', 'black'),
  ('Fishing', 'fishing', 'Terms and activities related to fishing', '🎣', 'blue'),
  ('Fitness Training', 'fitness-training', 'Terms and activities related to fitness training', '💪', 'red'),
  ('Flag Football', 'flag-football', 'Terms and activities related to flag football', '🏈', 'orange'),
  ('Floral Design', 'floral-design', 'Terms and activities related to floral design', '🌱', 'pink'),
  ('Flower Arranging', 'flower-arranging', 'Terms and activities related to flower arranging', '🌱', 'pink'),
  ('Fly Fishing', 'fly-fishing', 'Terms and activities related to fly fishing', '🎣', 'blue'),
  ('Football', 'football', 'Terms and activities related to football', '🏈', 'brown'),
  ('Foraging', 'foraging', 'Terms and activities related to foraging', '🍄', 'green'),
  ('Fossil Hunting', 'fossil-hunting', 'Terms and activities related to fossil hunting', '🎯', 'brown'),
  ('Frisbee', 'frisbee', 'Terms and activities related to frisbee', '🎯', 'yellow'),
  ('Furniture Restoration', 'furniture-restoration', 'Terms and activities related to furniture restoration', '🪵', 'brown'),
  ('Gardening', 'gardening', 'Terms and activities related to gardening', '🌱', 'green'),
  ('Genealogy', 'genealogy', 'Terms and activities related to genealogy', '📜', 'brown'),
  ('Geocaching', 'geocaching', 'Terms and activities related to geocaching', '🗺️', 'green'),
  ('Geology', 'geology', 'Terms and activities related to geology', '🪨', 'brown'),
  ('Glassblowing', 'glassblowing', 'Terms and activities related to glassblowing', '🫧', 'blue'),
  ('Go-karting', 'go-karting', 'Terms and activities related to go-karting', '🏎️', 'yellow'),
  ('Golf', 'golf', 'Terms and activities related to golf', '⛳', 'green'),
  ('Graffiti', 'graffiti', 'Terms and activities related to graffiti', '🎨', 'red'),
  ('Guitar Playing', 'guitar-playing', 'Terms and activities related to guitar playing', '🎸', 'brown'),
  ('Gymnastics', 'gymnastics', 'Terms and activities related to gymnastics', '🤸', 'pink'),
  ('Ham Radio', 'ham-radio', 'Terms and activities related to ham radio', '📻', 'red'),
  ('Handball', 'handball', 'Terms and activities related to handball', '🎯', 'orange'),
  ('Hang Gliding', 'hang-gliding', 'Terms and activities related to hang gliding', '🪂', 'blue'),
  ('Hiking', 'hiking', 'Terms and activities related to hiking', '🥾', 'green'),
  ('Hockey', 'hockey', 'Terms and activities related to hockey', '🏒', 'black'),
  ('Home Brewing', 'home-brewing', 'Terms and activities related to home brewing', '🍺', 'brown'),
  ('Horse Racing', 'horse-racing', 'Terms and activities related to horse racing', '🐴', 'brown'),
  ('Horseback Riding', 'horseback-riding', 'Terms and activities related to horseback riding', '🐴', 'brown'),
  ('Hot Air Ballooning', 'hot-air-ballooning', 'Terms and activities related to hot air ballooning', '🎯', 'red'),
  ('Hunting', 'hunting', 'Terms and activities related to hunting', '🏹', 'brown'),
  ('Ice Hockey', 'ice-hockey', 'Terms and activities related to ice hockey', '🏒', 'black'),
  ('Ice Skating', 'ice-skating', 'Terms and activities related to ice skating', '⛸️', 'blue'),
  ('Improv Comedy', 'improv-comedy', 'Terms and activities related to improv comedy', '🎭', 'yellow'),
  ('Inline Skating', 'inline-skating', 'Terms and activities related to inline skating', '🎯', 'blue'),
  ('Interior Design', 'interior-design', 'Terms and activities related to interior design', '🏠', 'purple'),
  ('Jewelry Making', 'jewelry-making', 'Terms and activities related to jewelry making', '💎', 'purple'),
  ('Jigsaw Puzzles', 'jigsaw-puzzles', 'Terms and activities related to jigsaw puzzles', '🧩', 'rainbow'),
  ('Jiu-jitsu', 'jiu-jitsu', 'Terms and activities related to jiu-jitsu', '🥋', 'white'),
  ('Jogging', 'jogging', 'Terms and activities related to jogging', '🏃', 'blue'),
  ('Journaling', 'journaling', 'Terms and activities related to journaling', '✍️', 'brown'),
  ('Judo', 'judo', 'Terms and activities related to judo', '🥋', 'white'),
  ('Juggling', 'juggling', 'Terms and activities related to juggling', '🤹', 'rainbow'),
  ('Karaoke', 'karaoke', 'Terms and activities related to karaoke', '🎤', 'pink'),
  ('Karate', 'karate', 'Terms and activities related to karate', '🥋', 'orange'),
  ('Kayaking', 'kayaking', 'Terms and activities related to kayaking', '🛶', 'blue'),
  ('Kite Flying', 'kite-flying', 'Terms and activities related to kite flying', '🎯', 'yellow'),
  ('Kitesurfing', 'kitesurfing', 'Terms and activities related to kitesurfing', '🏄', 'blue'),
  ('Knitting', 'knitting', 'Terms and activities related to knitting', '🧶', 'blue'),
  ('Lacrosse', 'lacrosse', 'Terms and activities related to lacrosse', '🎯', 'orange'),
  ('Language Learning', 'language-learning', 'Terms and activities related to language learning', '🗣️', 'blue'),
  ('Lapidary', 'lapidary', 'Terms and activities related to lapidary', '💎', 'purple'),
  ('Leather Working', 'leather-working', 'Terms and activities related to leather working', '👜', 'brown'),
  ('Lego Building', 'lego-building', 'Terms and activities related to lego building', '🔨', 'red'),
  ('Longboarding', 'longboarding', 'Terms and activities related to longboarding', '🛹', 'blue'),
  ('Magic Tricks', 'magic-tricks', 'Terms and activities related to magic tricks', '🎩', 'black'),
  ('Marathon Running', 'marathon-running', 'Terms and activities related to marathon running', '🏃', 'red'),
  ('Martial Arts', 'martial-arts', 'Terms and activities related to martial arts', '🥋', 'red'),
  ('Meditation', 'meditation', 'Terms and activities related to meditation', '🧘‍♀️', 'purple'),
  ('Metal Detecting', 'metal-detecting', 'Terms and activities related to metal detecting', '🎯', 'gray'),
  ('Metalworking', 'metalworking', 'Terms and activities related to metalworking', '🔨', 'gray'),
  ('Meteorology', 'meteorology', 'Terms and activities related to meteorology', '🌤️', 'blue'),
  ('Mineral Collecting', 'mineral-collecting', 'Terms and activities related to mineral collecting', '📦', 'gray'),
  ('Mixed Martial Arts', 'mixed-martial-arts', 'Terms and activities related to mixed martial arts', '🥊', 'red'),
  ('Model Aircraft', 'model-aircraft', 'Terms and activities related to model aircraft', '✈️', 'blue'),
  ('Model Building', 'model-building', 'Terms and activities related to model building', '✈️', 'gray'),
  ('Model Railroading', 'model-railroading', 'Terms and activities related to model railroading', '🚂', 'green'),
  ('Motorcycling', 'motorcycling', 'Terms and activities related to motorcycling', '🏍️', 'black'),
  ('Mountain Biking', 'mountain-biking', 'Terms and activities related to mountain biking', '🚴', 'green'),
  ('Mountaineering', 'mountaineering', 'Terms and activities related to mountaineering', '🏔️', 'white'),
  ('Movie Collecting', 'movie-collecting', 'Terms and activities related to movie collecting', '📦', 'purple'),
  ('Mushroom Hunting', 'mushroom-hunting', 'Terms and activities related to mushroom hunting', '🍄', 'brown'),
  ('Music Composition', 'music-composition', 'Terms and activities related to music composition', '🎵', 'blue'),
  ('Nail Art', 'nail-art', 'Terms and activities related to nail art', '🎨', 'pink'),
  ('Needlepoint', 'needlepoint', 'Terms and activities related to needlepoint', '🧵', 'pink'),
  ('Netball', 'netball', 'Terms and activities related to netball', '🎯', 'orange'),
  ('Orienteering', 'orienteering', 'Terms and activities related to orienteering', '🧭', 'green'),
  ('Origami', 'origami', 'Terms and activities related to origami', '🎯', 'yellow'),
  ('Paintball', 'paintball', 'Terms and activities related to paintball', '🎯', 'green'),
  ('Painting', 'painting', 'Terms and activities related to painting', '🎨', 'red'),
  ('Paper Making', 'paper-making', 'Terms and activities related to paper making', '📦', 'brown'),
  ('Paragliding', 'paragliding', 'Terms and activities related to paragliding', '🪂', 'yellow'),
  ('Parkour', 'parkour', 'Terms and activities related to parkour', '🤸‍♂️', 'gray'),
  ('Pet Training', 'pet-training', 'Terms and activities related to pet training', '🐕', 'blue'),
  ('Photography', 'photography', 'Terms and activities related to photography', '📷', 'purple'),
  ('Piano', 'piano', 'Terms and activities related to piano', '🎹', 'black'),
  ('Pilates', 'pilates', 'Terms and activities related to pilates', '🤸', 'pink'),
  ('Ping Pong', 'ping-pong', 'Terms and activities related to ping pong', '🏓', 'orange'),
  ('Playing Musical Instruments', 'playing-musical-instruments', 'Terms and activities related to playing musical instruments', '🎵', 'blue'),
  ('Podcasting', 'podcasting', 'Terms and activities related to podcasting', '🎙️', 'red'),
  ('Poetry Writing', 'poetry-writing', 'Terms and activities related to poetry writing', '✍️', 'purple'),
  ('Poker', 'poker', 'Terms and activities related to poker', '🃏', 'red'),
  ('Pole Dancing', 'pole-dancing', 'Terms and activities related to pole dancing', '💃', 'pink'),
  ('Pottery', 'pottery', 'Terms and activities related to pottery', '🏺', 'brown'),
  ('Powerlifting', 'powerlifting', 'Terms and activities related to powerlifting', '🏋️', 'red'),
  ('Public Speaking', 'public-speaking', 'Terms and activities related to public speaking', '🎤', 'red'),
  ('Puppetry', 'puppetry', 'Terms and activities related to puppetry', '🎪', 'red'),
  ('Puzzles', 'puzzles', 'Terms and activities related to puzzles', '🧩', 'rainbow'),
  ('Quilting', 'quilting', 'Terms and activities related to quilting', '🧵', 'pink'),
  ('Racing', 'racing', 'Terms and activities related to racing', '🏎️', 'red'),
  ('Radio Control', 'radio-control', 'Terms and activities related to radio control', '📡', 'blue'),
  ('Rafting', 'rafting', 'Terms and activities related to rafting', '🛶', 'blue'),
  ('Rapping', 'rapping', 'Terms and activities related to rapping', '🎤', 'orange'),
  ('Reading', 'reading', 'Terms and activities related to reading', '📚', 'brown'),
  ('Record Collecting', 'record-collecting', 'Terms and activities related to record collecting', '📦', 'purple'),
  ('Remote Control Racing', 'remote-control-racing', 'Terms and activities related to remote control racing', '📡', 'red'),
  ('Road Biking', 'road-biking', 'Terms and activities related to road biking', '🚴', 'blue'),
  ('Robotics', 'robotics', 'Terms and activities related to robotics', '🤖', 'gray'),
  ('Rock Climbing', 'rock-climbing', 'Terms and activities related to rock climbing', '🧗‍♀️', 'brown'),
  ('Roller Derby', 'roller-derby', 'Terms and activities related to roller derby', '🎯', 'pink'),
  ('Roller Skating', 'roller-skating', 'Terms and activities related to roller skating', '🎯', 'yellow'),
  ('Rowing', 'rowing', 'Terms and activities related to rowing', '🛶', 'blue'),
  ('Rugby', 'rugby', 'Terms and activities related to rugby', '🏉', 'brown'),
  ('Running', 'running', 'Terms and activities related to running', '🏃', 'blue'),
  ('Sailing', 'sailing', 'Terms and activities related to sailing', '⛵', 'blue'),
  ('Salsa Dancing', 'salsa-dancing', 'Terms and activities related to salsa dancing', '💃', 'red'),
  ('Sand Art', 'sand-art', 'Terms and activities related to sand art', '🎨', 'yellow'),
  ('Scrapbooking', 'scrapbooking', 'Terms and activities related to scrapbooking', '📦', 'pink'),
  ('Scuba Diving', 'scuba-diving', 'Terms and activities related to scuba diving', '🤿', 'blue'),
  ('Sculling Or Rowing', 'sculling-or-rowing', 'Terms and activities related to sculling or rowing', '🛶', 'blue'),
  ('Sculpting', 'sculpting', 'Terms and activities related to sculpting', '🎨', 'gray'),
  ('Sewing', 'sewing', 'Terms and activities related to sewing', '🪡', 'blue'),
  ('Shooting', 'shooting', 'Terms and activities related to shooting', '🎯', 'black'),
  ('Shopping', 'shopping', 'Terms and activities related to shopping', '🛍️', 'pink'),
  ('Singing', 'singing', 'Terms and activities related to singing', '🎤', 'yellow'),
  ('Skateboarding', 'skateboarding', 'Terms and activities related to skateboarding', '🛹', 'gray'),
  ('Skiing', 'skiing', 'Terms and activities related to skiing', '⛷️', 'blue'),
  ('Skimboarding', 'skimboarding', 'Terms and activities related to skimboarding', '🏄', 'teal'),
  ('Skydiving', 'skydiving', 'Terms and activities related to skydiving', '🪂', 'blue'),
  ('Slacklining', 'slacklining', 'Terms and activities related to slacklining', '🎯', 'green'),
  ('Snorkeling', 'snorkeling', 'Terms and activities related to snorkeling', '🤿', 'teal'),
  ('Snowboarding', 'snowboarding', 'Terms and activities related to snowboarding', '🏂', 'blue'),
  ('Soap Making', 'soap-making', 'Terms and activities related to soap making', '✂️', 'pink'),
  ('Soccer', 'soccer', 'Terms and activities related to soccer', '⚽', 'green'),
  ('Softball', 'softball', 'Terms and activities related to softball', '⚾', 'yellow'),
  ('Spelunking', 'spelunking', 'Terms and activities related to spelunking', '🎯', 'brown'),
  ('Squash', 'squash', 'Terms and activities related to squash', '🎾', 'yellow'),
  ('Stamp Collecting', 'stamp-collecting', 'Terms and activities related to stamp collecting', '📮', 'blue'),
  ('Stand-up Comedy', 'stand-up-comedy', 'Terms and activities related to stand-up comedy', '🎤', 'yellow'),
  ('Stargazing', 'stargazing', 'Terms and activities related to stargazing', '🔭', 'purple'),
  ('Stone Skipping', 'stone-skipping', 'Terms and activities related to stone skipping', '🎯', 'blue'),
  ('Storytelling', 'storytelling', 'Terms and activities related to storytelling', '📚', 'yellow'),
  ('Sudoku', 'sudoku', 'Terms and activities related to sudoku', '🔢', 'blue'),
  ('Surfing', 'surfing', 'Terms and activities related to surfing', '🏄‍♂️', 'blue'),
  ('Swimming', 'swimming', 'Terms and activities related to swimming', '🏊', 'blue'),
  ('Table Tennis', 'table-tennis', 'Terms and activities related to table tennis', '🏓', 'orange'),
  ('Tai Chi', 'tai-chi', 'Terms and activities related to tai chi', '☯️', 'blue'),
  ('Tarot Reading', 'tarot-reading', 'Terms and activities related to tarot reading', '🎯', 'purple'),
  ('Tattooing', 'tattooing', 'Terms and activities related to tattooing', '🎨', 'black'),
  ('Tennis', 'tennis', 'Terms and activities related to tennis', '🎾', 'yellow'),
  ('Textiles', 'textiles', 'Terms and activities related to textiles', '🧵', 'blue'),
  ('Theater', 'theater', 'Terms and activities related to theater', '🎭', 'red'),
  ('Track And Field', 'track-and-field', 'Terms and activities related to track and field', '🏃', 'blue'),
  ('Trainspotting', 'trainspotting', 'Terms and activities related to trainspotting', '🚂', 'green'),
  ('Triathlon', 'triathlon', 'Terms and activities related to triathlon', '🏃', 'orange'),
  ('Trivia', 'trivia', 'Terms and activities related to trivia', '🧠', 'purple'),
  ('Ultimate Frisbee', 'ultimate-frisbee', 'Terms and activities related to ultimate frisbee', '🎯', 'yellow'),
  ('Unicycling', 'unicycling', 'Terms and activities related to unicycling', '🎯', 'blue'),
  ('Video Gaming', 'video-gaming', 'Terms and activities related to video gaming', '🎮', 'blue'),
  ('Violin', 'violin', 'Terms and activities related to violin', '🎻', 'brown'),
  ('Volleyball', 'volleyball', 'Terms and activities related to volleyball', '🏐', 'white'),
  ('Walking', 'walking', 'Terms and activities related to walking', '🚶', 'green'),
  ('Water Polo', 'water-polo', 'Terms and activities related to water polo', '🏊', 'blue'),
  ('Water Skiing', 'water-skiing', 'Terms and activities related to water skiing', '🎿', 'blue'),
  ('Weaving', 'weaving', 'Terms and activities related to weaving', '✂️', 'brown'),
  ('Web Design', 'web-design', 'Terms and activities related to web design', '🌐', 'blue'),
  ('Weightlifting', 'weightlifting', 'Terms and activities related to weightlifting', '🏋️', 'red'),
  ('Whale Watching', 'whale-watching', 'Terms and activities related to whale watching', '🐋', 'blue'),
  ('Wine Making', 'wine-making', 'Terms and activities related to wine making', '🍷', 'purple'),
  ('Wine Tasting', 'wine-tasting', 'Terms and activities related to wine tasting', '🍷', 'purple'),
  ('Woodworking', 'woodworking', 'Terms and activities related to woodworking', '🪵', 'brown'),
  ('Wrestling', 'wrestling', 'Terms and activities related to wrestling', '🤼', 'blue'),
  ('Writing', 'writing', 'Terms and activities related to writing', '✍️', 'black'),
  ('Yoga', 'yoga', 'Terms and activities related to yoga', '🧘', 'purple'),
  ('Yoyo', 'yoyo', 'Terms and activities related to yoyo', '🎯', 'yellow'),
  ('Zumba', 'zumba', 'Terms and activities related to zumba', '💃', 'pink')
ON CONFLICT (slug) DO NOTHING;